stages:
    - deploy

pages:
    stage: deploy
    image: python:latest
    only:
        - master
    script:
        - make develop
        - make docs
        - mv docs/_build/html public
    artifacts:
        paths:
            - public
