# SPDX-Copyright: 2017-2018 Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

stages:
    - test
    - deploy

before_script:
    - apt-get -qq update
    - apt-get -qq install -y cmake libgit2-dev >> /dev/null

.run_tox: &tox_definition
    stage: test
    script:
        - pip install tox
        - tox
    tags:
        - docker
py35-test:
    <<: *tox_definition
    image: python:3.5
    script:
        - sed -i '/^black/d' requirements.txt
        - pip install tox
        - tox
    variables:
        TOXENV: py35-test

py36-test:
    <<: *tox_definition
    image: python:3.6
    variables:
        TOXENV: py36-test

py37-test:
    <<: *tox_definition
    image: python:3.7
    variables:
        TOXENV: py37-test

lint:
    <<: *tox_definition
    image: python:3.6
    variables:
        TOXENV: lint

docs:
    <<: *tox_definition
    image: python:3.6
    variables:
        TOXENV: docs
    artifacts:
        paths:
            - docs/_build/html

pages:
    stage: deploy
    image: python:latest
    only:
        - /v[0-9]+.*/
    dependencies:
        - docs
    script:
        - mv docs/_build/html public
    artifacts:
        paths:
            - public
