stages:
    - deploy

pages:
    stage: deploy
    image: python:latest
    only:
        - master
    script:
        - apt-get -qq update
        - apt-get -y -qq install build-essential cmake
        - python3 -mvenv venv
        - source venv/bin/activate
        - make develop
        - make docs
        - mv docs/_build/html public
    artifacts:
        paths:
            - public
