# SPDX-FileCopyrightText: 2017-2019 Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: GPL-3.0-or-later

stages:
    - test

.run_tox: &tox_definition
    stage: test
    script:
        - pip install tox
        - tox
    tags:
        - docker
py36-test:
    <<: *tox_definition
    image: python:3.6
    variables:
        TOXENV: py36-test

py37-test:
    <<: *tox_definition
    image: python:3.7
    variables:
        TOXENV: py37-test

py38-test:
    <<: *tox_definition
    image: python:3.8-rc
    variables:
        TOXENV: py38-test

lint:
    <<: *tox_definition
    image: python:3.6
    variables:
        TOXENV: lint

docs:
    <<: *tox_definition
    image: python:3.6
    variables:
        TOXENV: docs
    artifacts:
        paths:
            - docs/_build/html
