# SPDX-FileCopyrightText: © 2020 Liferay, Inc. <https://liferay.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Verify that the license lists are up-to-date

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  latest-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: latest
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Verify that the license lists are up-to-date
      run: |
        python .github/workflows/license_list_up_to_date.py
